// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: fof/v1/fof.proto

package fofv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LatLng struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat float64 `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng float64 `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
}

func (x *LatLng) Reset() {
	*x = LatLng{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fof_v1_fof_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LatLng) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatLng) ProtoMessage() {}

func (x *LatLng) ProtoReflect() protoreflect.Message {
	mi := &file_fof_v1_fof_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatLng.ProtoReflect.Descriptor instead.
func (*LatLng) Descriptor() ([]byte, []int) {
	return file_fof_v1_fof_proto_rawDescGZIP(), []int{0}
}

func (x *LatLng) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *LatLng) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type GetClearedAreaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetClearedAreaRequest) Reset() {
	*x = GetClearedAreaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fof_v1_fof_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetClearedAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClearedAreaRequest) ProtoMessage() {}

func (x *GetClearedAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fof_v1_fof_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClearedAreaRequest.ProtoReflect.Descriptor instead.
func (*GetClearedAreaRequest) Descriptor() ([]byte, []int) {
	return file_fof_v1_fof_proto_rawDescGZIP(), []int{1}
}

type GetClearedAreaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClearedAreaGeojson string `protobuf:"bytes,1,opt,name=cleared_area_geojson,json=clearedAreaGeojson,proto3" json:"cleared_area_geojson,omitempty"`
}

func (x *GetClearedAreaResponse) Reset() {
	*x = GetClearedAreaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fof_v1_fof_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetClearedAreaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClearedAreaResponse) ProtoMessage() {}

func (x *GetClearedAreaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fof_v1_fof_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClearedAreaResponse.ProtoReflect.Descriptor instead.
func (*GetClearedAreaResponse) Descriptor() ([]byte, []int) {
	return file_fof_v1_fof_proto_rawDescGZIP(), []int{2}
}

func (x *GetClearedAreaResponse) GetClearedAreaGeojson() string {
	if x != nil {
		return x.ClearedAreaGeojson
	}
	return ""
}

type CreateVisitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopId string `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
}

func (x *CreateVisitRequest) Reset() {
	*x = CreateVisitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fof_v1_fof_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVisitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVisitRequest) ProtoMessage() {}

func (x *CreateVisitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fof_v1_fof_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVisitRequest.ProtoReflect.Descriptor instead.
func (*CreateVisitRequest) Descriptor() ([]byte, []int) {
	return file_fof_v1_fof_proto_rawDescGZIP(), []int{3}
}

func (x *CreateVisitRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

type CreateVisitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success            bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ClearedAreaGeojson string `protobuf:"bytes,2,opt,name=cleared_area_geojson,json=clearedAreaGeojson,proto3" json:"cleared_area_geojson,omitempty"`
}

func (x *CreateVisitResponse) Reset() {
	*x = CreateVisitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fof_v1_fof_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVisitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVisitResponse) ProtoMessage() {}

func (x *CreateVisitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fof_v1_fof_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVisitResponse.ProtoReflect.Descriptor instead.
func (*CreateVisitResponse) Descriptor() ([]byte, []int) {
	return file_fof_v1_fof_proto_rawDescGZIP(), []int{4}
}

func (x *CreateVisitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateVisitResponse) GetClearedAreaGeojson() string {
	if x != nil {
		return x.ClearedAreaGeojson
	}
	return ""
}

type UpdateLocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path     []*LatLng `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
	Accuracy float64   `protobuf:"fixed64,2,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
}

func (x *UpdateLocationRequest) Reset() {
	*x = UpdateLocationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fof_v1_fof_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationRequest) ProtoMessage() {}

func (x *UpdateLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fof_v1_fof_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateLocationRequest) Descriptor() ([]byte, []int) {
	return file_fof_v1_fof_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateLocationRequest) GetPath() []*LatLng {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *UpdateLocationRequest) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

type UpdateLocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewlyCleared       bool   `protobuf:"varint,1,opt,name=newly_cleared,json=newlyCleared,proto3" json:"newly_cleared,omitempty"` // True if new area was unlocked
	ClearedAreaGeojson string `protobuf:"bytes,2,opt,name=cleared_area_geojson,json=clearedAreaGeojson,proto3" json:"cleared_area_geojson,omitempty"`
}

func (x *UpdateLocationResponse) Reset() {
	*x = UpdateLocationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fof_v1_fof_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationResponse) ProtoMessage() {}

func (x *UpdateLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fof_v1_fof_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationResponse.ProtoReflect.Descriptor instead.
func (*UpdateLocationResponse) Descriptor() ([]byte, []int) {
	return file_fof_v1_fof_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateLocationResponse) GetNewlyCleared() bool {
	if x != nil {
		return x.NewlyCleared
	}
	return false
}

func (x *UpdateLocationResponse) GetClearedAreaGeojson() string {
	if x != nil {
		return x.ClearedAreaGeojson
	}
	return ""
}

type GetNearbyShopsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat                  float64 `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float64 `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	RadiusMeters         float64 `protobuf:"fixed64,3,opt,name=radius_meters,json=radiusMeters,proto3" json:"radius_meters,omitempty"`
	ExclusiveIndependent bool    `protobuf:"varint,4,opt,name=exclusive_independent,json=exclusiveIndependent,proto3" json:"exclusive_independent,omitempty"` // Filter for indie shops only
}

func (x *GetNearbyShopsRequest) Reset() {
	*x = GetNearbyShopsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fof_v1_fof_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNearbyShopsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNearbyShopsRequest) ProtoMessage() {}

func (x *GetNearbyShopsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fof_v1_fof_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNearbyShopsRequest.ProtoReflect.Descriptor instead.
func (*GetNearbyShopsRequest) Descriptor() ([]byte, []int) {
	return file_fof_v1_fof_proto_rawDescGZIP(), []int{7}
}

func (x *GetNearbyShopsRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GetNearbyShopsRequest) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *GetNearbyShopsRequest) GetRadiusMeters() float64 {
	if x != nil {
		return x.RadiusMeters
	}
	return 0
}

func (x *GetNearbyShopsRequest) GetExclusiveIndependent() bool {
	if x != nil {
		return x.ExclusiveIndependent
	}
	return false
}

type GetNearbyShopsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shops []*Shop `protobuf:"bytes,1,rep,name=shops,proto3" json:"shops,omitempty"`
}

func (x *GetNearbyShopsResponse) Reset() {
	*x = GetNearbyShopsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fof_v1_fof_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNearbyShopsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNearbyShopsResponse) ProtoMessage() {}

func (x *GetNearbyShopsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fof_v1_fof_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNearbyShopsResponse.ProtoReflect.Descriptor instead.
func (*GetNearbyShopsResponse) Descriptor() ([]byte, []int) {
	return file_fof_v1_fof_proto_rawDescGZIP(), []int{8}
}

func (x *GetNearbyShopsResponse) GetShops() []*Shop {
	if x != nil {
		return x.Shops
	}
	return nil
}

type GetVisitedShopsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetVisitedShopsRequest) Reset() {
	*x = GetVisitedShopsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fof_v1_fof_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVisitedShopsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVisitedShopsRequest) ProtoMessage() {}

func (x *GetVisitedShopsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fof_v1_fof_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVisitedShopsRequest.ProtoReflect.Descriptor instead.
func (*GetVisitedShopsRequest) Descriptor() ([]byte, []int) {
	return file_fof_v1_fof_proto_rawDescGZIP(), []int{9}
}

type GetVisitedShopsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shops []*Shop `protobuf:"bytes,1,rep,name=shops,proto3" json:"shops,omitempty"`
}

func (x *GetVisitedShopsResponse) Reset() {
	*x = GetVisitedShopsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fof_v1_fof_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVisitedShopsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVisitedShopsResponse) ProtoMessage() {}

func (x *GetVisitedShopsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fof_v1_fof_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVisitedShopsResponse.ProtoReflect.Descriptor instead.
func (*GetVisitedShopsResponse) Descriptor() ([]byte, []int) {
	return file_fof_v1_fof_proto_rawDescGZIP(), []int{10}
}

func (x *GetVisitedShopsResponse) GetShops() []*Shop {
	if x != nil {
		return x.Shops
	}
	return nil
}

type Shop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Lat          float64  `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng          float64  `protobuf:"fixed64,4,opt,name=lng,proto3" json:"lng,omitempty"`
	Category     string   `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	IsVisited    bool     `protobuf:"varint,6,opt,name=is_visited,json=isVisited,proto3" json:"is_visited,omitempty"`
	IsChain      bool     `protobuf:"varint,7,opt,name=is_chain,json=isChain,proto3" json:"is_chain,omitempty"`
	Address      string   `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	Phone        string   `protobuf:"bytes,9,opt,name=phone,proto3" json:"phone,omitempty"`
	OpeningHours string   `protobuf:"bytes,10,opt,name=opening_hours,json=openingHours,proto3" json:"opening_hours,omitempty"`
	ImageUrls    []string `protobuf:"bytes,11,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	Rating       float64  `protobuf:"fixed64,12,opt,name=rating,proto3" json:"rating,omitempty"`
	SourceUrl    string   `protobuf:"bytes,13,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
}

func (x *Shop) Reset() {
	*x = Shop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fof_v1_fof_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Shop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shop) ProtoMessage() {}

func (x *Shop) ProtoReflect() protoreflect.Message {
	mi := &file_fof_v1_fof_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shop.ProtoReflect.Descriptor instead.
func (*Shop) Descriptor() ([]byte, []int) {
	return file_fof_v1_fof_proto_rawDescGZIP(), []int{11}
}

func (x *Shop) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Shop) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Shop) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Shop) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *Shop) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Shop) GetIsVisited() bool {
	if x != nil {
		return x.IsVisited
	}
	return false
}

func (x *Shop) GetIsChain() bool {
	if x != nil {
		return x.IsChain
	}
	return false
}

func (x *Shop) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Shop) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Shop) GetOpeningHours() string {
	if x != nil {
		return x.OpeningHours
	}
	return ""
}

func (x *Shop) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *Shop) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Shop) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

var File_fof_v1_fof_proto protoreflect.FileDescriptor

var file_fof_v1_fof_proto_rawDesc = []byte{
	0x0a, 0x10, 0x66, 0x6f, 0x66, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x6f, 0x66, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x66, 0x6f, 0x66, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2c, 0x0a, 0x06, 0x4c, 0x61, 0x74, 0x4c,
	0x6e, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x03, 0x6c, 0x6e, 0x67, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x65,
	0x61, 0x72, 0x65, 0x64, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x4a, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x65, 0x64, 0x41, 0x72, 0x65,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x14, 0x63, 0x6c, 0x65,
	0x61, 0x72, 0x65, 0x64, 0x5f, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x67, 0x65, 0x6f, 0x6a, 0x73, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x65, 0x64,
	0x41, 0x72, 0x65, 0x61, 0x47, 0x65, 0x6f, 0x6a, 0x73, 0x6f, 0x6e, 0x22, 0x2d, 0x0a, 0x12, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x69, 0x73, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x22, 0x61, 0x0a, 0x13, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x56, 0x69, 0x73, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x30, 0x0a, 0x14, 0x63,
	0x6c, 0x65, 0x61, 0x72, 0x65, 0x64, 0x5f, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x67, 0x65, 0x6f, 0x6a,
	0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x63, 0x6c, 0x65, 0x61, 0x72,
	0x65, 0x64, 0x41, 0x72, 0x65, 0x61, 0x47, 0x65, 0x6f, 0x6a, 0x73, 0x6f, 0x6e, 0x22, 0x57, 0x0a,
	0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x66, 0x6f, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x61,
	0x74, 0x4c, 0x6e, 0x67, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63,
	0x63, 0x75, 0x72, 0x61, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x61, 0x63,
	0x63, 0x75, 0x72, 0x61, 0x63, 0x79, 0x22, 0x6f, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x23, 0x0a, 0x0d, 0x6e, 0x65, 0x77, 0x6c, 0x79, 0x5f, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x6e, 0x65, 0x77, 0x6c, 0x79, 0x43, 0x6c,
	0x65, 0x61, 0x72, 0x65, 0x64, 0x12, 0x30, 0x0a, 0x14, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x65, 0x64,
	0x5f, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x67, 0x65, 0x6f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x12, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x65, 0x64, 0x41, 0x72, 0x65, 0x61,
	0x47, 0x65, 0x6f, 0x6a, 0x73, 0x6f, 0x6e, 0x22, 0x95, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4e,
	0x65, 0x61, 0x72, 0x62, 0x79, 0x53, 0x68, 0x6f, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03,
	0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x03, 0x6c, 0x6e, 0x67, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x5f,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x72, 0x61,
	0x64, 0x69, 0x75, 0x73, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x33, 0x0a, 0x15, 0x65, 0x78,
	0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64,
	0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x14, 0x65, 0x78, 0x63, 0x6c, 0x75,
	0x73, 0x69, 0x76, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x74, 0x22,
	0x3c, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x53, 0x68, 0x6f, 0x70,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x73, 0x68, 0x6f,
	0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x66, 0x6f, 0x66, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x52, 0x05, 0x73, 0x68, 0x6f, 0x70, 0x73, 0x22, 0x18, 0x0a,
	0x16, 0x47, 0x65, 0x74, 0x56, 0x69, 0x73, 0x69, 0x74, 0x65, 0x64, 0x53, 0x68, 0x6f, 0x70, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3d, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x56, 0x69,
	0x73, 0x69, 0x74, 0x65, 0x64, 0x53, 0x68, 0x6f, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x73, 0x68, 0x6f, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x66, 0x6f, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x52,
	0x05, 0x73, 0x68, 0x6f, 0x70, 0x73, 0x22, 0xcf, 0x02, 0x0a, 0x04, 0x53, 0x68, 0x6f, 0x70, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x03, 0x6c, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x76, 0x69, 0x73, 0x69, 0x74, 0x65,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x56, 0x69, 0x73, 0x69, 0x74,
	0x65, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x23, 0x0a,
	0x0d, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x68, 0x6f, 0x75, 0x72, 0x73, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x75,
	0x72, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x73,
	0x18, 0x0b, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x72, 0x6c, 0x32, 0xa1, 0x04, 0x0a, 0x0d, 0x46, 0x6c, 0x61,
	0x76, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x68, 0x0a, 0x0e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x2e, 0x66,
	0x6f, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x66, 0x6f,
	0x66, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x11, 0x3a, 0x01, 0x2a, 0x22, 0x0c, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x69, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x61, 0x72, 0x62,
	0x79, 0x53, 0x68, 0x6f, 0x70, 0x73, 0x12, 0x1d, 0x2e, 0x66, 0x6f, 0x66, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x53, 0x68, 0x6f, 0x70, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x66, 0x6f, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x53, 0x68, 0x6f, 0x70, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x12, 0x10, 0x2f,
	0x76, 0x31, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x73, 0x2f, 0x6e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x12,
	0x6d, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x56, 0x69, 0x73, 0x69, 0x74, 0x65, 0x64, 0x53, 0x68, 0x6f,
	0x70, 0x73, 0x12, 0x1e, 0x2e, 0x66, 0x6f, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x56,
	0x69, 0x73, 0x69, 0x74, 0x65, 0x64, 0x53, 0x68, 0x6f, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x66, 0x6f, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x56,
	0x69, 0x73, 0x69, 0x74, 0x65, 0x64, 0x53, 0x68, 0x6f, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x11, 0x2f, 0x76, 0x31,
	0x2f, 0x73, 0x68, 0x6f, 0x70, 0x73, 0x2f, 0x76, 0x69, 0x73, 0x69, 0x74, 0x65, 0x64, 0x12, 0x5d,
	0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x69, 0x73, 0x69, 0x74, 0x12, 0x1a, 0x2e,
	0x66, 0x6f, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x69, 0x73,
	0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x66, 0x6f, 0x66, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x69, 0x73, 0x69, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x3a, 0x01,
	0x2a, 0x22, 0x0a, 0x2f, 0x76, 0x31, 0x2f, 0x76, 0x69, 0x73, 0x69, 0x74, 0x73, 0x12, 0x6d, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x65, 0x64, 0x41, 0x72, 0x65, 0x61, 0x12,
	0x1d, 0x2e, 0x66, 0x6f, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x65, 0x61,
	0x72, 0x65, 0x64, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x66, 0x6f, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x65, 0x61, 0x72,
	0x65, 0x64, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1c,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16, 0x12, 0x14, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x65, 0x64, 0x42, 0x29, 0x5a, 0x27,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x69, 0x75, 0x74, 0x73,
	0x2f, 0x66, 0x6f, 0x66, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76,
	0x31, 0x3b, 0x66, 0x6f, 0x66, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fof_v1_fof_proto_rawDescOnce sync.Once
	file_fof_v1_fof_proto_rawDescData = file_fof_v1_fof_proto_rawDesc
)

func file_fof_v1_fof_proto_rawDescGZIP() []byte {
	file_fof_v1_fof_proto_rawDescOnce.Do(func() {
		file_fof_v1_fof_proto_rawDescData = protoimpl.X.CompressGZIP(file_fof_v1_fof_proto_rawDescData)
	})
	return file_fof_v1_fof_proto_rawDescData
}

var file_fof_v1_fof_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_fof_v1_fof_proto_goTypes = []interface{}{
	(*LatLng)(nil),                  // 0: fof.v1.LatLng
	(*GetClearedAreaRequest)(nil),   // 1: fof.v1.GetClearedAreaRequest
	(*GetClearedAreaResponse)(nil),  // 2: fof.v1.GetClearedAreaResponse
	(*CreateVisitRequest)(nil),      // 3: fof.v1.CreateVisitRequest
	(*CreateVisitResponse)(nil),     // 4: fof.v1.CreateVisitResponse
	(*UpdateLocationRequest)(nil),   // 5: fof.v1.UpdateLocationRequest
	(*UpdateLocationResponse)(nil),  // 6: fof.v1.UpdateLocationResponse
	(*GetNearbyShopsRequest)(nil),   // 7: fof.v1.GetNearbyShopsRequest
	(*GetNearbyShopsResponse)(nil),  // 8: fof.v1.GetNearbyShopsResponse
	(*GetVisitedShopsRequest)(nil),  // 9: fof.v1.GetVisitedShopsRequest
	(*GetVisitedShopsResponse)(nil), // 10: fof.v1.GetVisitedShopsResponse
	(*Shop)(nil),                    // 11: fof.v1.Shop
}
var file_fof_v1_fof_proto_depIdxs = []int32{
	0,  // 0: fof.v1.UpdateLocationRequest.path:type_name -> fof.v1.LatLng
	11, // 1: fof.v1.GetNearbyShopsResponse.shops:type_name -> fof.v1.Shop
	11, // 2: fof.v1.GetVisitedShopsResponse.shops:type_name -> fof.v1.Shop
	5,  // 3: fof.v1.FlavorService.UpdateLocation:input_type -> fof.v1.UpdateLocationRequest
	7,  // 4: fof.v1.FlavorService.GetNearbyShops:input_type -> fof.v1.GetNearbyShopsRequest
	9,  // 5: fof.v1.FlavorService.GetVisitedShops:input_type -> fof.v1.GetVisitedShopsRequest
	3,  // 6: fof.v1.FlavorService.CreateVisit:input_type -> fof.v1.CreateVisitRequest
	1,  // 7: fof.v1.FlavorService.GetClearedArea:input_type -> fof.v1.GetClearedAreaRequest
	6,  // 8: fof.v1.FlavorService.UpdateLocation:output_type -> fof.v1.UpdateLocationResponse
	8,  // 9: fof.v1.FlavorService.GetNearbyShops:output_type -> fof.v1.GetNearbyShopsResponse
	10, // 10: fof.v1.FlavorService.GetVisitedShops:output_type -> fof.v1.GetVisitedShopsResponse
	4,  // 11: fof.v1.FlavorService.CreateVisit:output_type -> fof.v1.CreateVisitResponse
	2,  // 12: fof.v1.FlavorService.GetClearedArea:output_type -> fof.v1.GetClearedAreaResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_fof_v1_fof_proto_init() }
func file_fof_v1_fof_proto_init() {
	if File_fof_v1_fof_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fof_v1_fof_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LatLng); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fof_v1_fof_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetClearedAreaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fof_v1_fof_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetClearedAreaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fof_v1_fof_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVisitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fof_v1_fof_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVisitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fof_v1_fof_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLocationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fof_v1_fof_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLocationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fof_v1_fof_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNearbyShopsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fof_v1_fof_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNearbyShopsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fof_v1_fof_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVisitedShopsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fof_v1_fof_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVisitedShopsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fof_v1_fof_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Shop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fof_v1_fof_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fof_v1_fof_proto_goTypes,
		DependencyIndexes: file_fof_v1_fof_proto_depIdxs,
		MessageInfos:      file_fof_v1_fof_proto_msgTypes,
	}.Build()
	File_fof_v1_fof_proto = out.File
	file_fof_v1_fof_proto_rawDesc = nil
	file_fof_v1_fof_proto_goTypes = nil
	file_fof_v1_fof_proto_depIdxs = nil
}
