// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: fof/v1/quest.proto

package fofv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	QuestService_StartQuest_FullMethodName      = "/fof.v1.QuestService/StartQuest"
	QuestService_CompleteQuest_FullMethodName   = "/fof.v1.QuestService/CompleteQuest"
	QuestService_CancelQuest_FullMethodName     = "/fof.v1.QuestService/CancelQuest"
	QuestService_GetActiveQuest_FullMethodName  = "/fof.v1.QuestService/GetActiveQuest"
	QuestService_GetQuestHistory_FullMethodName = "/fof.v1.QuestService/GetQuestHistory"
)

// QuestServiceClient is the client API for QuestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuestServiceClient interface {
	// Start a new quest to a shop
	StartQuest(ctx context.Context, in *StartQuestRequest, opts ...grpc.CallOption) (*StartQuestResponse, error)
	// Complete the active quest
	CompleteQuest(ctx context.Context, in *CompleteQuestRequest, opts ...grpc.CallOption) (*CompleteQuestResponse, error)
	// Cancel the active quest
	CancelQuest(ctx context.Context, in *CancelQuestRequest, opts ...grpc.CallOption) (*CancelQuestResponse, error)
	// Get the user's active quest
	GetActiveQuest(ctx context.Context, in *GetActiveQuestRequest, opts ...grpc.CallOption) (*GetActiveQuestResponse, error)
	// Get the user's quest history
	GetQuestHistory(ctx context.Context, in *GetQuestHistoryRequest, opts ...grpc.CallOption) (*GetQuestHistoryResponse, error)
}

type questServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuestServiceClient(cc grpc.ClientConnInterface) QuestServiceClient {
	return &questServiceClient{cc}
}

func (c *questServiceClient) StartQuest(ctx context.Context, in *StartQuestRequest, opts ...grpc.CallOption) (*StartQuestResponse, error) {
	out := new(StartQuestResponse)
	err := c.cc.Invoke(ctx, QuestService_StartQuest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questServiceClient) CompleteQuest(ctx context.Context, in *CompleteQuestRequest, opts ...grpc.CallOption) (*CompleteQuestResponse, error) {
	out := new(CompleteQuestResponse)
	err := c.cc.Invoke(ctx, QuestService_CompleteQuest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questServiceClient) CancelQuest(ctx context.Context, in *CancelQuestRequest, opts ...grpc.CallOption) (*CancelQuestResponse, error) {
	out := new(CancelQuestResponse)
	err := c.cc.Invoke(ctx, QuestService_CancelQuest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questServiceClient) GetActiveQuest(ctx context.Context, in *GetActiveQuestRequest, opts ...grpc.CallOption) (*GetActiveQuestResponse, error) {
	out := new(GetActiveQuestResponse)
	err := c.cc.Invoke(ctx, QuestService_GetActiveQuest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questServiceClient) GetQuestHistory(ctx context.Context, in *GetQuestHistoryRequest, opts ...grpc.CallOption) (*GetQuestHistoryResponse, error) {
	out := new(GetQuestHistoryResponse)
	err := c.cc.Invoke(ctx, QuestService_GetQuestHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuestServiceServer is the server API for QuestService service.
// All implementations must embed UnimplementedQuestServiceServer
// for forward compatibility
type QuestServiceServer interface {
	// Start a new quest to a shop
	StartQuest(context.Context, *StartQuestRequest) (*StartQuestResponse, error)
	// Complete the active quest
	CompleteQuest(context.Context, *CompleteQuestRequest) (*CompleteQuestResponse, error)
	// Cancel the active quest
	CancelQuest(context.Context, *CancelQuestRequest) (*CancelQuestResponse, error)
	// Get the user's active quest
	GetActiveQuest(context.Context, *GetActiveQuestRequest) (*GetActiveQuestResponse, error)
	// Get the user's quest history
	GetQuestHistory(context.Context, *GetQuestHistoryRequest) (*GetQuestHistoryResponse, error)
	mustEmbedUnimplementedQuestServiceServer()
}

// UnimplementedQuestServiceServer must be embedded to have forward compatible implementations.
type UnimplementedQuestServiceServer struct {
}

func (UnimplementedQuestServiceServer) StartQuest(context.Context, *StartQuestRequest) (*StartQuestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartQuest not implemented")
}
func (UnimplementedQuestServiceServer) CompleteQuest(context.Context, *CompleteQuestRequest) (*CompleteQuestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteQuest not implemented")
}
func (UnimplementedQuestServiceServer) CancelQuest(context.Context, *CancelQuestRequest) (*CancelQuestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelQuest not implemented")
}
func (UnimplementedQuestServiceServer) GetActiveQuest(context.Context, *GetActiveQuestRequest) (*GetActiveQuestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveQuest not implemented")
}
func (UnimplementedQuestServiceServer) GetQuestHistory(context.Context, *GetQuestHistoryRequest) (*GetQuestHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuestHistory not implemented")
}
func (UnimplementedQuestServiceServer) mustEmbedUnimplementedQuestServiceServer() {}

// UnsafeQuestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuestServiceServer will
// result in compilation errors.
type UnsafeQuestServiceServer interface {
	mustEmbedUnimplementedQuestServiceServer()
}

func RegisterQuestServiceServer(s grpc.ServiceRegistrar, srv QuestServiceServer) {
	s.RegisterService(&QuestService_ServiceDesc, srv)
}

func _QuestService_StartQuest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartQuestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestServiceServer).StartQuest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestService_StartQuest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestServiceServer).StartQuest(ctx, req.(*StartQuestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestService_CompleteQuest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteQuestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestServiceServer).CompleteQuest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestService_CompleteQuest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestServiceServer).CompleteQuest(ctx, req.(*CompleteQuestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestService_CancelQuest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelQuestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestServiceServer).CancelQuest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestService_CancelQuest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestServiceServer).CancelQuest(ctx, req.(*CancelQuestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestService_GetActiveQuest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveQuestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestServiceServer).GetActiveQuest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestService_GetActiveQuest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestServiceServer).GetActiveQuest(ctx, req.(*GetActiveQuestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestService_GetQuestHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuestHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestServiceServer).GetQuestHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestService_GetQuestHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestServiceServer).GetQuestHistory(ctx, req.(*GetQuestHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuestService_ServiceDesc is the grpc.ServiceDesc for QuestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fof.v1.QuestService",
	HandlerType: (*QuestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartQuest",
			Handler:    _QuestService_StartQuest_Handler,
		},
		{
			MethodName: "CompleteQuest",
			Handler:    _QuestService_CompleteQuest_Handler,
		},
		{
			MethodName: "CancelQuest",
			Handler:    _QuestService_CancelQuest_Handler,
		},
		{
			MethodName: "GetActiveQuest",
			Handler:    _QuestService_GetActiveQuest_Handler,
		},
		{
			MethodName: "GetQuestHistory",
			Handler:    _QuestService_GetQuestHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fof/v1/quest.proto",
}
