// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: fof/v1/ranking.proto

package fofv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RankingService_GetAreaCoverageRanking_FullMethodName  = "/fof.v1.RankingService/GetAreaCoverageRanking"
	RankingService_GetLevelRanking_FullMethodName         = "/fof.v1.RankingService/GetLevelRanking"
	RankingService_GetVisitCountRanking_FullMethodName    = "/fof.v1.RankingService/GetVisitCountRanking"
	RankingService_GetCategoryVisitRanking_FullMethodName = "/fof.v1.RankingService/GetCategoryVisitRanking"
)

// RankingServiceClient is the client API for RankingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RankingServiceClient interface {
	// Get area coverage ranking (fog cleared area)
	GetAreaCoverageRanking(ctx context.Context, in *GetRankingRequest, opts ...grpc.CallOption) (*GetRankingResponse, error)
	// Get level ranking
	GetLevelRanking(ctx context.Context, in *GetRankingRequest, opts ...grpc.CallOption) (*GetRankingResponse, error)
	// Get visit count ranking
	GetVisitCountRanking(ctx context.Context, in *GetRankingRequest, opts ...grpc.CallOption) (*GetRankingResponse, error)
	// Get category-specific visit ranking
	GetCategoryVisitRanking(ctx context.Context, in *GetCategoryRankingRequest, opts ...grpc.CallOption) (*GetRankingResponse, error)
}

type rankingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRankingServiceClient(cc grpc.ClientConnInterface) RankingServiceClient {
	return &rankingServiceClient{cc}
}

func (c *rankingServiceClient) GetAreaCoverageRanking(ctx context.Context, in *GetRankingRequest, opts ...grpc.CallOption) (*GetRankingResponse, error) {
	out := new(GetRankingResponse)
	err := c.cc.Invoke(ctx, RankingService_GetAreaCoverageRanking_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankingServiceClient) GetLevelRanking(ctx context.Context, in *GetRankingRequest, opts ...grpc.CallOption) (*GetRankingResponse, error) {
	out := new(GetRankingResponse)
	err := c.cc.Invoke(ctx, RankingService_GetLevelRanking_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankingServiceClient) GetVisitCountRanking(ctx context.Context, in *GetRankingRequest, opts ...grpc.CallOption) (*GetRankingResponse, error) {
	out := new(GetRankingResponse)
	err := c.cc.Invoke(ctx, RankingService_GetVisitCountRanking_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankingServiceClient) GetCategoryVisitRanking(ctx context.Context, in *GetCategoryRankingRequest, opts ...grpc.CallOption) (*GetRankingResponse, error) {
	out := new(GetRankingResponse)
	err := c.cc.Invoke(ctx, RankingService_GetCategoryVisitRanking_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RankingServiceServer is the server API for RankingService service.
// All implementations must embed UnimplementedRankingServiceServer
// for forward compatibility
type RankingServiceServer interface {
	// Get area coverage ranking (fog cleared area)
	GetAreaCoverageRanking(context.Context, *GetRankingRequest) (*GetRankingResponse, error)
	// Get level ranking
	GetLevelRanking(context.Context, *GetRankingRequest) (*GetRankingResponse, error)
	// Get visit count ranking
	GetVisitCountRanking(context.Context, *GetRankingRequest) (*GetRankingResponse, error)
	// Get category-specific visit ranking
	GetCategoryVisitRanking(context.Context, *GetCategoryRankingRequest) (*GetRankingResponse, error)
	mustEmbedUnimplementedRankingServiceServer()
}

// UnimplementedRankingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRankingServiceServer struct {
}

func (UnimplementedRankingServiceServer) GetAreaCoverageRanking(context.Context, *GetRankingRequest) (*GetRankingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAreaCoverageRanking not implemented")
}
func (UnimplementedRankingServiceServer) GetLevelRanking(context.Context, *GetRankingRequest) (*GetRankingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLevelRanking not implemented")
}
func (UnimplementedRankingServiceServer) GetVisitCountRanking(context.Context, *GetRankingRequest) (*GetRankingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVisitCountRanking not implemented")
}
func (UnimplementedRankingServiceServer) GetCategoryVisitRanking(context.Context, *GetCategoryRankingRequest) (*GetRankingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategoryVisitRanking not implemented")
}
func (UnimplementedRankingServiceServer) mustEmbedUnimplementedRankingServiceServer() {}

// UnsafeRankingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RankingServiceServer will
// result in compilation errors.
type UnsafeRankingServiceServer interface {
	mustEmbedUnimplementedRankingServiceServer()
}

func RegisterRankingServiceServer(s grpc.ServiceRegistrar, srv RankingServiceServer) {
	s.RegisterService(&RankingService_ServiceDesc, srv)
}

func _RankingService_GetAreaCoverageRanking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRankingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServiceServer).GetAreaCoverageRanking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankingService_GetAreaCoverageRanking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServiceServer).GetAreaCoverageRanking(ctx, req.(*GetRankingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RankingService_GetLevelRanking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRankingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServiceServer).GetLevelRanking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankingService_GetLevelRanking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServiceServer).GetLevelRanking(ctx, req.(*GetRankingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RankingService_GetVisitCountRanking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRankingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServiceServer).GetVisitCountRanking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankingService_GetVisitCountRanking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServiceServer).GetVisitCountRanking(ctx, req.(*GetRankingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RankingService_GetCategoryVisitRanking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryRankingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServiceServer).GetCategoryVisitRanking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankingService_GetCategoryVisitRanking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServiceServer).GetCategoryVisitRanking(ctx, req.(*GetCategoryRankingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RankingService_ServiceDesc is the grpc.ServiceDesc for RankingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RankingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fof.v1.RankingService",
	HandlerType: (*RankingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAreaCoverageRanking",
			Handler:    _RankingService_GetAreaCoverageRanking_Handler,
		},
		{
			MethodName: "GetLevelRanking",
			Handler:    _RankingService_GetLevelRanking_Handler,
		},
		{
			MethodName: "GetVisitCountRanking",
			Handler:    _RankingService_GetVisitCountRanking_Handler,
		},
		{
			MethodName: "GetCategoryVisitRanking",
			Handler:    _RankingService_GetCategoryVisitRanking_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fof/v1/ranking.proto",
}
