// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: fof/v1/visit.proto

package fofv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	VisitService_GetVisitedShops_FullMethodName = "/fof.v1.VisitService/GetVisitedShops"
	VisitService_CreateVisit_FullMethodName     = "/fof.v1.VisitService/CreateVisit"
	VisitService_UpdateVisit_FullMethodName     = "/fof.v1.VisitService/UpdateVisit"
)

// VisitServiceClient is the client API for VisitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VisitServiceClient interface {
	// Get list of visited shops for highlighting
	GetVisitedShops(ctx context.Context, in *GetVisitedShopsRequest, opts ...grpc.CallOption) (*GetVisitedShopsResponse, error)
	// Manually register a visit to a shop
	CreateVisit(ctx context.Context, in *CreateVisitRequest, opts ...grpc.CallOption) (*CreateVisitResponse, error)
	// Update a visit review
	UpdateVisit(ctx context.Context, in *UpdateVisitRequest, opts ...grpc.CallOption) (*UpdateVisitResponse, error)
}

type visitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVisitServiceClient(cc grpc.ClientConnInterface) VisitServiceClient {
	return &visitServiceClient{cc}
}

func (c *visitServiceClient) GetVisitedShops(ctx context.Context, in *GetVisitedShopsRequest, opts ...grpc.CallOption) (*GetVisitedShopsResponse, error) {
	out := new(GetVisitedShopsResponse)
	err := c.cc.Invoke(ctx, VisitService_GetVisitedShops_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visitServiceClient) CreateVisit(ctx context.Context, in *CreateVisitRequest, opts ...grpc.CallOption) (*CreateVisitResponse, error) {
	out := new(CreateVisitResponse)
	err := c.cc.Invoke(ctx, VisitService_CreateVisit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visitServiceClient) UpdateVisit(ctx context.Context, in *UpdateVisitRequest, opts ...grpc.CallOption) (*UpdateVisitResponse, error) {
	out := new(UpdateVisitResponse)
	err := c.cc.Invoke(ctx, VisitService_UpdateVisit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VisitServiceServer is the server API for VisitService service.
// All implementations must embed UnimplementedVisitServiceServer
// for forward compatibility
type VisitServiceServer interface {
	// Get list of visited shops for highlighting
	GetVisitedShops(context.Context, *GetVisitedShopsRequest) (*GetVisitedShopsResponse, error)
	// Manually register a visit to a shop
	CreateVisit(context.Context, *CreateVisitRequest) (*CreateVisitResponse, error)
	// Update a visit review
	UpdateVisit(context.Context, *UpdateVisitRequest) (*UpdateVisitResponse, error)
	mustEmbedUnimplementedVisitServiceServer()
}

// UnimplementedVisitServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVisitServiceServer struct {
}

func (UnimplementedVisitServiceServer) GetVisitedShops(context.Context, *GetVisitedShopsRequest) (*GetVisitedShopsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVisitedShops not implemented")
}
func (UnimplementedVisitServiceServer) CreateVisit(context.Context, *CreateVisitRequest) (*CreateVisitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVisit not implemented")
}
func (UnimplementedVisitServiceServer) UpdateVisit(context.Context, *UpdateVisitRequest) (*UpdateVisitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVisit not implemented")
}
func (UnimplementedVisitServiceServer) mustEmbedUnimplementedVisitServiceServer() {}

// UnsafeVisitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VisitServiceServer will
// result in compilation errors.
type UnsafeVisitServiceServer interface {
	mustEmbedUnimplementedVisitServiceServer()
}

func RegisterVisitServiceServer(s grpc.ServiceRegistrar, srv VisitServiceServer) {
	s.RegisterService(&VisitService_ServiceDesc, srv)
}

func _VisitService_GetVisitedShops_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVisitedShopsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisitServiceServer).GetVisitedShops(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisitService_GetVisitedShops_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisitServiceServer).GetVisitedShops(ctx, req.(*GetVisitedShopsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisitService_CreateVisit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVisitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisitServiceServer).CreateVisit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisitService_CreateVisit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisitServiceServer).CreateVisit(ctx, req.(*CreateVisitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisitService_UpdateVisit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVisitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisitServiceServer).UpdateVisit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisitService_UpdateVisit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisitServiceServer).UpdateVisit(ctx, req.(*UpdateVisitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VisitService_ServiceDesc is the grpc.ServiceDesc for VisitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VisitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fof.v1.VisitService",
	HandlerType: (*VisitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVisitedShops",
			Handler:    _VisitService_GetVisitedShops_Handler,
		},
		{
			MethodName: "CreateVisit",
			Handler:    _VisitService_CreateVisit_Handler,
		},
		{
			MethodName: "UpdateVisit",
			Handler:    _VisitService_UpdateVisit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fof/v1/visit.proto",
}
