// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: api/proto/v1/fof.proto

package fofv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	Accuracy      float64                `protobuf:"fixed64,3,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLocationRequest) Reset() {
	*x = UpdateLocationRequest{}
	mi := &file_api_proto_v1_fof_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationRequest) ProtoMessage() {}

func (x *UpdateLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_fof_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateLocationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_fof_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateLocationRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *UpdateLocationRequest) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *UpdateLocationRequest) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

type UpdateLocationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NewlyCleared   bool                   `protobuf:"varint,1,opt,name=newly_cleared,json=newlyCleared,proto3" json:"newly_cleared,omitempty"` // True if new area was unlocked
	ClearedTileIds []string               `protobuf:"bytes,2,rep,name=cleared_tile_ids,json=clearedTileIds,proto3" json:"cleared_tile_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateLocationResponse) Reset() {
	*x = UpdateLocationResponse{}
	mi := &file_api_proto_v1_fof_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationResponse) ProtoMessage() {}

func (x *UpdateLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_fof_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationResponse.ProtoReflect.Descriptor instead.
func (*UpdateLocationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_fof_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateLocationResponse) GetNewlyCleared() bool {
	if x != nil {
		return x.NewlyCleared
	}
	return false
}

func (x *UpdateLocationResponse) GetClearedTileIds() []string {
	if x != nil {
		return x.ClearedTileIds
	}
	return nil
}

type GetNearbyShopsRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Lat                  float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	RadiusMeters         float64                `protobuf:"fixed64,3,opt,name=radius_meters,json=radiusMeters,proto3" json:"radius_meters,omitempty"`
	ExclusiveIndependent bool                   `protobuf:"varint,4,opt,name=exclusive_independent,json=exclusiveIndependent,proto3" json:"exclusive_independent,omitempty"` // Filter for indie shops only
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetNearbyShopsRequest) Reset() {
	*x = GetNearbyShopsRequest{}
	mi := &file_api_proto_v1_fof_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNearbyShopsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNearbyShopsRequest) ProtoMessage() {}

func (x *GetNearbyShopsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_fof_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNearbyShopsRequest.ProtoReflect.Descriptor instead.
func (*GetNearbyShopsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_fof_proto_rawDescGZIP(), []int{2}
}

func (x *GetNearbyShopsRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GetNearbyShopsRequest) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *GetNearbyShopsRequest) GetRadiusMeters() float64 {
	if x != nil {
		return x.RadiusMeters
	}
	return 0
}

func (x *GetNearbyShopsRequest) GetExclusiveIndependent() bool {
	if x != nil {
		return x.ExclusiveIndependent
	}
	return false
}

type GetNearbyShopsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shops         []*Shop                `protobuf:"bytes,1,rep,name=shops,proto3" json:"shops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNearbyShopsResponse) Reset() {
	*x = GetNearbyShopsResponse{}
	mi := &file_api_proto_v1_fof_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNearbyShopsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNearbyShopsResponse) ProtoMessage() {}

func (x *GetNearbyShopsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_fof_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNearbyShopsResponse.ProtoReflect.Descriptor instead.
func (*GetNearbyShopsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_fof_proto_rawDescGZIP(), []int{3}
}

func (x *GetNearbyShopsResponse) GetShops() []*Shop {
	if x != nil {
		return x.Shops
	}
	return nil
}

type GetVisitedShopsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVisitedShopsRequest) Reset() {
	*x = GetVisitedShopsRequest{}
	mi := &file_api_proto_v1_fof_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVisitedShopsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVisitedShopsRequest) ProtoMessage() {}

func (x *GetVisitedShopsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_fof_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVisitedShopsRequest.ProtoReflect.Descriptor instead.
func (*GetVisitedShopsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_fof_proto_rawDescGZIP(), []int{4}
}

type GetVisitedShopsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shops         []*Shop                `protobuf:"bytes,1,rep,name=shops,proto3" json:"shops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVisitedShopsResponse) Reset() {
	*x = GetVisitedShopsResponse{}
	mi := &file_api_proto_v1_fof_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVisitedShopsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVisitedShopsResponse) ProtoMessage() {}

func (x *GetVisitedShopsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_fof_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVisitedShopsResponse.ProtoReflect.Descriptor instead.
func (*GetVisitedShopsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_fof_proto_rawDescGZIP(), []int{5}
}

func (x *GetVisitedShopsResponse) GetShops() []*Shop {
	if x != nil {
		return x.Shops
	}
	return nil
}

type Shop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Lat           float64                `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,4,opt,name=lng,proto3" json:"lng,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	IsVisited     bool                   `protobuf:"varint,6,opt,name=is_visited,json=isVisited,proto3" json:"is_visited,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shop) Reset() {
	*x = Shop{}
	mi := &file_api_proto_v1_fof_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shop) ProtoMessage() {}

func (x *Shop) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_fof_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shop.ProtoReflect.Descriptor instead.
func (*Shop) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_fof_proto_rawDescGZIP(), []int{6}
}

func (x *Shop) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Shop) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Shop) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Shop) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *Shop) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Shop) GetIsVisited() bool {
	if x != nil {
		return x.IsVisited
	}
	return false
}

var File_api_proto_v1_fof_proto protoreflect.FileDescriptor

const file_api_proto_v1_fof_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/v1/fof.proto\x12\x06fof.v1\x1a\x1cgoogle/api/annotations.proto\"W\n" +
	"\x15UpdateLocationRequest\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\x12\x1a\n" +
	"\baccuracy\x18\x03 \x01(\x01R\baccuracy\"g\n" +
	"\x16UpdateLocationResponse\x12#\n" +
	"\rnewly_cleared\x18\x01 \x01(\bR\fnewlyCleared\x12(\n" +
	"\x10cleared_tile_ids\x18\x02 \x03(\tR\x0eclearedTileIds\"\x95\x01\n" +
	"\x15GetNearbyShopsRequest\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\x12#\n" +
	"\rradius_meters\x18\x03 \x01(\x01R\fradiusMeters\x123\n" +
	"\x15exclusive_independent\x18\x04 \x01(\bR\x14exclusiveIndependent\"<\n" +
	"\x16GetNearbyShopsResponse\x12\"\n" +
	"\x05shops\x18\x01 \x03(\v2\f.fof.v1.ShopR\x05shops\"\x18\n" +
	"\x16GetVisitedShopsRequest\"=\n" +
	"\x17GetVisitedShopsResponse\x12\"\n" +
	"\x05shops\x18\x01 \x03(\v2\f.fof.v1.ShopR\x05shops\"\x89\x01\n" +
	"\x04Shop\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03lat\x18\x03 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x04 \x01(\x01R\x03lng\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x1d\n" +
	"\n" +
	"is_visited\x18\x06 \x01(\bR\tisVisited2\xd3\x02\n" +
	"\rFlavorService\x12h\n" +
	"\x0eUpdateLocation\x12\x1d.fof.v1.UpdateLocationRequest\x1a\x1e.fof.v1.UpdateLocationResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/location\x12i\n" +
	"\x0eGetNearbyShops\x12\x1d.fof.v1.GetNearbyShopsRequest\x1a\x1e.fof.v1.GetNearbyShopsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/shops/nearby\x12m\n" +
	"\x0fGetVisitedShops\x12\x1e.fof.v1.GetVisitedShopsRequest\x1a\x1f.fof.v1.GetVisitedShopsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/shops/visitedB)Z'github.com/viuts/fof/api/proto/v1;fofv1b\x06proto3"

var (
	file_api_proto_v1_fof_proto_rawDescOnce sync.Once
	file_api_proto_v1_fof_proto_rawDescData []byte
)

func file_api_proto_v1_fof_proto_rawDescGZIP() []byte {
	file_api_proto_v1_fof_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_fof_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_fof_proto_rawDesc), len(file_api_proto_v1_fof_proto_rawDesc)))
	})
	return file_api_proto_v1_fof_proto_rawDescData
}

var file_api_proto_v1_fof_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_v1_fof_proto_goTypes = []any{
	(*UpdateLocationRequest)(nil),   // 0: fof.v1.UpdateLocationRequest
	(*UpdateLocationResponse)(nil),  // 1: fof.v1.UpdateLocationResponse
	(*GetNearbyShopsRequest)(nil),   // 2: fof.v1.GetNearbyShopsRequest
	(*GetNearbyShopsResponse)(nil),  // 3: fof.v1.GetNearbyShopsResponse
	(*GetVisitedShopsRequest)(nil),  // 4: fof.v1.GetVisitedShopsRequest
	(*GetVisitedShopsResponse)(nil), // 5: fof.v1.GetVisitedShopsResponse
	(*Shop)(nil),                    // 6: fof.v1.Shop
}
var file_api_proto_v1_fof_proto_depIdxs = []int32{
	6, // 0: fof.v1.GetNearbyShopsResponse.shops:type_name -> fof.v1.Shop
	6, // 1: fof.v1.GetVisitedShopsResponse.shops:type_name -> fof.v1.Shop
	0, // 2: fof.v1.FlavorService.UpdateLocation:input_type -> fof.v1.UpdateLocationRequest
	2, // 3: fof.v1.FlavorService.GetNearbyShops:input_type -> fof.v1.GetNearbyShopsRequest
	4, // 4: fof.v1.FlavorService.GetVisitedShops:input_type -> fof.v1.GetVisitedShopsRequest
	1, // 5: fof.v1.FlavorService.UpdateLocation:output_type -> fof.v1.UpdateLocationResponse
	3, // 6: fof.v1.FlavorService.GetNearbyShops:output_type -> fof.v1.GetNearbyShopsResponse
	5, // 7: fof.v1.FlavorService.GetVisitedShops:output_type -> fof.v1.GetVisitedShopsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_v1_fof_proto_init() }
func file_api_proto_v1_fof_proto_init() {
	if File_api_proto_v1_fof_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_fof_proto_rawDesc), len(file_api_proto_v1_fof_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_fof_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_fof_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_fof_proto_msgTypes,
	}.Build()
	File_api_proto_v1_fof_proto = out.File
	file_api_proto_v1_fof_proto_goTypes = nil
	file_api_proto_v1_fof_proto_depIdxs = nil
}
