// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: api/proto/v1/fof.proto

package fofv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FlavorService_UpdateLocation_FullMethodName  = "/fof.v1.FlavorService/UpdateLocation"
	FlavorService_GetNearbyShops_FullMethodName  = "/fof.v1.FlavorService/GetNearbyShops"
	FlavorService_GetVisitedShops_FullMethodName = "/fof.v1.FlavorService/GetVisitedShops"
)

// FlavorServiceClient is the client API for FlavorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlavorServiceClient interface {
	// Clear fog on the map (Send current location)
	UpdateLocation(ctx context.Context, in *UpdateLocationRequest, opts ...grpc.CallOption) (*UpdateLocationResponse, error)
	// Get nearby unvisited indie shops (For Quest/Explore mode)
	GetNearbyShops(ctx context.Context, in *GetNearbyShopsRequest, opts ...grpc.CallOption) (*GetNearbyShopsResponse, error)
	// Get list of visited shops for highlighting
	GetVisitedShops(ctx context.Context, in *GetVisitedShopsRequest, opts ...grpc.CallOption) (*GetVisitedShopsResponse, error)
}

type flavorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlavorServiceClient(cc grpc.ClientConnInterface) FlavorServiceClient {
	return &flavorServiceClient{cc}
}

func (c *flavorServiceClient) UpdateLocation(ctx context.Context, in *UpdateLocationRequest, opts ...grpc.CallOption) (*UpdateLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateLocationResponse)
	err := c.cc.Invoke(ctx, FlavorService_UpdateLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flavorServiceClient) GetNearbyShops(ctx context.Context, in *GetNearbyShopsRequest, opts ...grpc.CallOption) (*GetNearbyShopsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNearbyShopsResponse)
	err := c.cc.Invoke(ctx, FlavorService_GetNearbyShops_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flavorServiceClient) GetVisitedShops(ctx context.Context, in *GetVisitedShopsRequest, opts ...grpc.CallOption) (*GetVisitedShopsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVisitedShopsResponse)
	err := c.cc.Invoke(ctx, FlavorService_GetVisitedShops_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlavorServiceServer is the server API for FlavorService service.
// All implementations must embed UnimplementedFlavorServiceServer
// for forward compatibility.
type FlavorServiceServer interface {
	// Clear fog on the map (Send current location)
	UpdateLocation(context.Context, *UpdateLocationRequest) (*UpdateLocationResponse, error)
	// Get nearby unvisited indie shops (For Quest/Explore mode)
	GetNearbyShops(context.Context, *GetNearbyShopsRequest) (*GetNearbyShopsResponse, error)
	// Get list of visited shops for highlighting
	GetVisitedShops(context.Context, *GetVisitedShopsRequest) (*GetVisitedShopsResponse, error)
	mustEmbedUnimplementedFlavorServiceServer()
}

// UnimplementedFlavorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlavorServiceServer struct{}

func (UnimplementedFlavorServiceServer) UpdateLocation(context.Context, *UpdateLocationRequest) (*UpdateLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLocation not implemented")
}
func (UnimplementedFlavorServiceServer) GetNearbyShops(context.Context, *GetNearbyShopsRequest) (*GetNearbyShopsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNearbyShops not implemented")
}
func (UnimplementedFlavorServiceServer) GetVisitedShops(context.Context, *GetVisitedShopsRequest) (*GetVisitedShopsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVisitedShops not implemented")
}
func (UnimplementedFlavorServiceServer) mustEmbedUnimplementedFlavorServiceServer() {}
func (UnimplementedFlavorServiceServer) testEmbeddedByValue()                       {}

// UnsafeFlavorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlavorServiceServer will
// result in compilation errors.
type UnsafeFlavorServiceServer interface {
	mustEmbedUnimplementedFlavorServiceServer()
}

func RegisterFlavorServiceServer(s grpc.ServiceRegistrar, srv FlavorServiceServer) {
	// If the following call pancis, it indicates UnimplementedFlavorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FlavorService_ServiceDesc, srv)
}

func _FlavorService_UpdateLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlavorServiceServer).UpdateLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlavorService_UpdateLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlavorServiceServer).UpdateLocation(ctx, req.(*UpdateLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlavorService_GetNearbyShops_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNearbyShopsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlavorServiceServer).GetNearbyShops(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlavorService_GetNearbyShops_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlavorServiceServer).GetNearbyShops(ctx, req.(*GetNearbyShopsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlavorService_GetVisitedShops_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVisitedShopsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlavorServiceServer).GetVisitedShops(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlavorService_GetVisitedShops_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlavorServiceServer).GetVisitedShops(ctx, req.(*GetVisitedShopsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FlavorService_ServiceDesc is the grpc.ServiceDesc for FlavorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlavorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fof.v1.FlavorService",
	HandlerType: (*FlavorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateLocation",
			Handler:    _FlavorService_UpdateLocation_Handler,
		},
		{
			MethodName: "GetNearbyShops",
			Handler:    _FlavorService_GetNearbyShops_Handler,
		},
		{
			MethodName: "GetVisitedShops",
			Handler:    _FlavorService_GetVisitedShops_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/fof.proto",
}
