// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDryTSatrZmjvKQwmQsguY6crkT7En6Fi8',
    appId: '1:1056282680716:web:bf34da0cc924d484484aa9',
    messagingSenderId: '1056282680716',
    projectId: 'dev-fof',
    authDomain: 'dev-fof.firebaseapp.com',
    storageBucket: 'dev-fof.firebasestorage.app',
    measurementId: 'G-ZCLXXW4SJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFrhV0HC1Z34pPJUnCop6L-9NUHW3P9eU',
    appId: '1:1056282680716:android:4168b5e72a086d2c484aa9',
    messagingSenderId: '1056282680716',
    projectId: 'dev-fof',
    storageBucket: 'dev-fof.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjO82YcMSDkEq3QRqKRGPQSZtYsI7U2gM',
    appId: '1:1056282680716:ios:9d30990b6fad101d484aa9',
    messagingSenderId: '1056282680716',
    projectId: 'dev-fof',
    storageBucket: 'dev-fof.firebasestorage.app',
    iosClientId: '1056282680716-igc3nl277kebv0ai96eq46fpa0iv6qe2.apps.googleusercontent.com',
    iosBundleId: 'com.viuts.fof',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjO82YcMSDkEq3QRqKRGPQSZtYsI7U2gM',
    appId: '1:1056282680716:ios:9d30990b6fad101d484aa9',
    messagingSenderId: '1056282680716',
    projectId: 'dev-fof',
    storageBucket: 'dev-fof.firebasestorage.app',
    iosClientId: '1056282680716-igc3nl277kebv0ai96eq46fpa0iv6qe2.apps.googleusercontent.com',
    iosBundleId: 'com.viuts.fof',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDryTSatrZmjvKQwmQsguY6crkT7En6Fi8',
    appId: '1:1056282680716:web:0f8420987334e608484aa9',
    messagingSenderId: '1056282680716',
    projectId: 'dev-fof',
    authDomain: 'dev-fof.firebaseapp.com',
    storageBucket: 'dev-fof.firebasestorage.app',
    measurementId: 'G-SVJSVV1NX1',
  );
}
