// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q       = new(Query)
	Shop    *shop
	User    *user
	UserFog *userFog
	Visit   *visit
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Shop = &Q.Shop
	User = &Q.User
	UserFog = &Q.UserFog
	Visit = &Q.Visit
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:      db,
		Shop:    newShop(db, opts...),
		User:    newUser(db, opts...),
		UserFog: newUserFog(db, opts...),
		Visit:   newVisit(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Shop    shop
	User    user
	UserFog userFog
	Visit   visit
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:      db,
		Shop:    q.Shop.clone(db),
		User:    q.User.clone(db),
		UserFog: q.UserFog.clone(db),
		Visit:   q.Visit.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:      db,
		Shop:    q.Shop.replaceDB(db),
		User:    q.User.replaceDB(db),
		UserFog: q.UserFog.replaceDB(db),
		Visit:   q.Visit.replaceDB(db),
	}
}

type queryCtx struct {
	Shop    IShopDo
	User    IUserDo
	UserFog IUserFogDo
	Visit   IVisitDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Shop:    q.Shop.WithContext(ctx),
		User:    q.User.WithContext(ctx),
		UserFog: q.UserFog.WithContext(ctx),
		Visit:   q.Visit.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
