// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/viuts/fof/apps/backend/internal/domain"
)

func newUserFog(db *gorm.DB, opts ...gen.DOOption) userFog {
	_userFog := userFog{}

	_userFog.userFogDo.UseDB(db, opts...)
	_userFog.userFogDo.UseModel(&domain.UserFog{})

	tableName := _userFog.userFogDo.TableName()
	_userFog.ALL = field.NewAsterisk(tableName)
	_userFog.UserID = field.NewField(tableName, "user_id")
	_userFog.ClearedArea = field.NewString(tableName, "cleared_area")
	_userFog.UpdatedAt = field.NewTime(tableName, "updated_at")

	_userFog.fillFieldMap()

	return _userFog
}

type userFog struct {
	userFogDo

	ALL         field.Asterisk
	UserID      field.Field
	ClearedArea field.String
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (u userFog) Table(newTableName string) *userFog {
	u.userFogDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userFog) As(alias string) *userFog {
	u.userFogDo.DO = *(u.userFogDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userFog) updateTableName(table string) *userFog {
	u.ALL = field.NewAsterisk(table)
	u.UserID = field.NewField(table, "user_id")
	u.ClearedArea = field.NewString(table, "cleared_area")
	u.UpdatedAt = field.NewTime(table, "updated_at")

	u.fillFieldMap()

	return u
}

func (u *userFog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userFog) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 3)
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["cleared_area"] = u.ClearedArea
	u.fieldMap["updated_at"] = u.UpdatedAt
}

func (u userFog) clone(db *gorm.DB) userFog {
	u.userFogDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userFog) replaceDB(db *gorm.DB) userFog {
	u.userFogDo.ReplaceDB(db)
	return u
}

type userFogDo struct{ gen.DO }

type IUserFogDo interface {
	gen.SubQuery
	Debug() IUserFogDo
	WithContext(ctx context.Context) IUserFogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserFogDo
	WriteDB() IUserFogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserFogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserFogDo
	Not(conds ...gen.Condition) IUserFogDo
	Or(conds ...gen.Condition) IUserFogDo
	Select(conds ...field.Expr) IUserFogDo
	Where(conds ...gen.Condition) IUserFogDo
	Order(conds ...field.Expr) IUserFogDo
	Distinct(cols ...field.Expr) IUserFogDo
	Omit(cols ...field.Expr) IUserFogDo
	Join(table schema.Tabler, on ...field.Expr) IUserFogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserFogDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserFogDo
	Group(cols ...field.Expr) IUserFogDo
	Having(conds ...gen.Condition) IUserFogDo
	Limit(limit int) IUserFogDo
	Offset(offset int) IUserFogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserFogDo
	Unscoped() IUserFogDo
	Create(values ...*domain.UserFog) error
	CreateInBatches(values []*domain.UserFog, batchSize int) error
	Save(values ...*domain.UserFog) error
	First() (*domain.UserFog, error)
	Take() (*domain.UserFog, error)
	Last() (*domain.UserFog, error)
	Find() ([]*domain.UserFog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.UserFog, err error)
	FindInBatches(result *[]*domain.UserFog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*domain.UserFog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserFogDo
	Assign(attrs ...field.AssignExpr) IUserFogDo
	Joins(fields ...field.RelationField) IUserFogDo
	Preload(fields ...field.RelationField) IUserFogDo
	FirstOrInit() (*domain.UserFog, error)
	FirstOrCreate() (*domain.UserFog, error)
	FindByPage(offset int, limit int) (result []*domain.UserFog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserFogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userFogDo) Debug() IUserFogDo {
	return u.withDO(u.DO.Debug())
}

func (u userFogDo) WithContext(ctx context.Context) IUserFogDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userFogDo) ReadDB() IUserFogDo {
	return u.Clauses(dbresolver.Read)
}

func (u userFogDo) WriteDB() IUserFogDo {
	return u.Clauses(dbresolver.Write)
}

func (u userFogDo) Session(config *gorm.Session) IUserFogDo {
	return u.withDO(u.DO.Session(config))
}

func (u userFogDo) Clauses(conds ...clause.Expression) IUserFogDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userFogDo) Returning(value interface{}, columns ...string) IUserFogDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userFogDo) Not(conds ...gen.Condition) IUserFogDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userFogDo) Or(conds ...gen.Condition) IUserFogDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userFogDo) Select(conds ...field.Expr) IUserFogDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userFogDo) Where(conds ...gen.Condition) IUserFogDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userFogDo) Order(conds ...field.Expr) IUserFogDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userFogDo) Distinct(cols ...field.Expr) IUserFogDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userFogDo) Omit(cols ...field.Expr) IUserFogDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userFogDo) Join(table schema.Tabler, on ...field.Expr) IUserFogDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userFogDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserFogDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userFogDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserFogDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userFogDo) Group(cols ...field.Expr) IUserFogDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userFogDo) Having(conds ...gen.Condition) IUserFogDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userFogDo) Limit(limit int) IUserFogDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userFogDo) Offset(offset int) IUserFogDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userFogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserFogDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userFogDo) Unscoped() IUserFogDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userFogDo) Create(values ...*domain.UserFog) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userFogDo) CreateInBatches(values []*domain.UserFog, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userFogDo) Save(values ...*domain.UserFog) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userFogDo) First() (*domain.UserFog, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.UserFog), nil
	}
}

func (u userFogDo) Take() (*domain.UserFog, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.UserFog), nil
	}
}

func (u userFogDo) Last() (*domain.UserFog, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.UserFog), nil
	}
}

func (u userFogDo) Find() ([]*domain.UserFog, error) {
	result, err := u.DO.Find()
	return result.([]*domain.UserFog), err
}

func (u userFogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.UserFog, err error) {
	buf := make([]*domain.UserFog, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userFogDo) FindInBatches(result *[]*domain.UserFog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userFogDo) Attrs(attrs ...field.AssignExpr) IUserFogDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userFogDo) Assign(attrs ...field.AssignExpr) IUserFogDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userFogDo) Joins(fields ...field.RelationField) IUserFogDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userFogDo) Preload(fields ...field.RelationField) IUserFogDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userFogDo) FirstOrInit() (*domain.UserFog, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.UserFog), nil
	}
}

func (u userFogDo) FirstOrCreate() (*domain.UserFog, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.UserFog), nil
	}
}

func (u userFogDo) FindByPage(offset int, limit int) (result []*domain.UserFog, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userFogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userFogDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userFogDo) Delete(models ...*domain.UserFog) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userFogDo) withDO(do gen.Dao) *userFogDo {
	u.DO = *do.(*gen.DO)
	return u
}
