// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/viuts/fof/apps/backend/internal/domain"
)

func newVisit(db *gorm.DB, opts ...gen.DOOption) visit {
	_visit := visit{}

	_visit.visitDo.UseDB(db, opts...)
	_visit.visitDo.UseModel(&domain.Visit{})

	tableName := _visit.visitDo.TableName()
	_visit.ALL = field.NewAsterisk(tableName)
	_visit.ID = field.NewField(tableName, "id")
	_visit.UserID = field.NewField(tableName, "user_id")
	_visit.ShopID = field.NewField(tableName, "shop_id")
	_visit.VisitedAt = field.NewTime(tableName, "visited_at")
	_visit.Rating = field.NewInt(tableName, "rating")
	_visit.Comment = field.NewString(tableName, "comment")
	_visit.Exp = field.NewInt(tableName, "exp")
	_visit.User = visitBelongsToUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "domain.User"),
	}

	_visit.Shop = visitBelongsToShop{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Shop", "domain.Shop"),
	}

	_visit.fillFieldMap()

	return _visit
}

type visit struct {
	visitDo

	ALL       field.Asterisk
	ID        field.Field
	UserID    field.Field
	ShopID    field.Field
	VisitedAt field.Time
	Rating    field.Int
	Comment   field.String
	Exp       field.Int
	User      visitBelongsToUser

	Shop visitBelongsToShop

	fieldMap map[string]field.Expr
}

func (v visit) Table(newTableName string) *visit {
	v.visitDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v visit) As(alias string) *visit {
	v.visitDo.DO = *(v.visitDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *visit) updateTableName(table string) *visit {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewField(table, "id")
	v.UserID = field.NewField(table, "user_id")
	v.ShopID = field.NewField(table, "shop_id")
	v.VisitedAt = field.NewTime(table, "visited_at")
	v.Rating = field.NewInt(table, "rating")
	v.Comment = field.NewString(table, "comment")
	v.Exp = field.NewInt(table, "exp")

	v.fillFieldMap()

	return v
}

func (v *visit) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *visit) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 9)
	v.fieldMap["id"] = v.ID
	v.fieldMap["user_id"] = v.UserID
	v.fieldMap["shop_id"] = v.ShopID
	v.fieldMap["visited_at"] = v.VisitedAt
	v.fieldMap["rating"] = v.Rating
	v.fieldMap["comment"] = v.Comment
	v.fieldMap["exp"] = v.Exp

}

func (v visit) clone(db *gorm.DB) visit {
	v.visitDo.ReplaceConnPool(db.Statement.ConnPool)
	v.User.db = db.Session(&gorm.Session{Initialized: true})
	v.User.db.Statement.ConnPool = db.Statement.ConnPool
	v.Shop.db = db.Session(&gorm.Session{Initialized: true})
	v.Shop.db.Statement.ConnPool = db.Statement.ConnPool
	return v
}

func (v visit) replaceDB(db *gorm.DB) visit {
	v.visitDo.ReplaceDB(db)
	v.User.db = db.Session(&gorm.Session{})
	v.Shop.db = db.Session(&gorm.Session{})
	return v
}

type visitBelongsToUser struct {
	db *gorm.DB

	field.RelationField
}

func (a visitBelongsToUser) Where(conds ...field.Expr) *visitBelongsToUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a visitBelongsToUser) WithContext(ctx context.Context) *visitBelongsToUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a visitBelongsToUser) Session(session *gorm.Session) *visitBelongsToUser {
	a.db = a.db.Session(session)
	return &a
}

func (a visitBelongsToUser) Model(m *domain.Visit) *visitBelongsToUserTx {
	return &visitBelongsToUserTx{a.db.Model(m).Association(a.Name())}
}

func (a visitBelongsToUser) Unscoped() *visitBelongsToUser {
	a.db = a.db.Unscoped()
	return &a
}

type visitBelongsToUserTx struct{ tx *gorm.Association }

func (a visitBelongsToUserTx) Find() (result *domain.User, err error) {
	return result, a.tx.Find(&result)
}

func (a visitBelongsToUserTx) Append(values ...*domain.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a visitBelongsToUserTx) Replace(values ...*domain.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a visitBelongsToUserTx) Delete(values ...*domain.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a visitBelongsToUserTx) Clear() error {
	return a.tx.Clear()
}

func (a visitBelongsToUserTx) Count() int64 {
	return a.tx.Count()
}

func (a visitBelongsToUserTx) Unscoped() *visitBelongsToUserTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type visitBelongsToShop struct {
	db *gorm.DB

	field.RelationField
}

func (a visitBelongsToShop) Where(conds ...field.Expr) *visitBelongsToShop {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a visitBelongsToShop) WithContext(ctx context.Context) *visitBelongsToShop {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a visitBelongsToShop) Session(session *gorm.Session) *visitBelongsToShop {
	a.db = a.db.Session(session)
	return &a
}

func (a visitBelongsToShop) Model(m *domain.Visit) *visitBelongsToShopTx {
	return &visitBelongsToShopTx{a.db.Model(m).Association(a.Name())}
}

func (a visitBelongsToShop) Unscoped() *visitBelongsToShop {
	a.db = a.db.Unscoped()
	return &a
}

type visitBelongsToShopTx struct{ tx *gorm.Association }

func (a visitBelongsToShopTx) Find() (result *domain.Shop, err error) {
	return result, a.tx.Find(&result)
}

func (a visitBelongsToShopTx) Append(values ...*domain.Shop) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a visitBelongsToShopTx) Replace(values ...*domain.Shop) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a visitBelongsToShopTx) Delete(values ...*domain.Shop) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a visitBelongsToShopTx) Clear() error {
	return a.tx.Clear()
}

func (a visitBelongsToShopTx) Count() int64 {
	return a.tx.Count()
}

func (a visitBelongsToShopTx) Unscoped() *visitBelongsToShopTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type visitDo struct{ gen.DO }

type IVisitDo interface {
	gen.SubQuery
	Debug() IVisitDo
	WithContext(ctx context.Context) IVisitDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IVisitDo
	WriteDB() IVisitDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IVisitDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IVisitDo
	Not(conds ...gen.Condition) IVisitDo
	Or(conds ...gen.Condition) IVisitDo
	Select(conds ...field.Expr) IVisitDo
	Where(conds ...gen.Condition) IVisitDo
	Order(conds ...field.Expr) IVisitDo
	Distinct(cols ...field.Expr) IVisitDo
	Omit(cols ...field.Expr) IVisitDo
	Join(table schema.Tabler, on ...field.Expr) IVisitDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IVisitDo
	RightJoin(table schema.Tabler, on ...field.Expr) IVisitDo
	Group(cols ...field.Expr) IVisitDo
	Having(conds ...gen.Condition) IVisitDo
	Limit(limit int) IVisitDo
	Offset(offset int) IVisitDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IVisitDo
	Unscoped() IVisitDo
	Create(values ...*domain.Visit) error
	CreateInBatches(values []*domain.Visit, batchSize int) error
	Save(values ...*domain.Visit) error
	First() (*domain.Visit, error)
	Take() (*domain.Visit, error)
	Last() (*domain.Visit, error)
	Find() ([]*domain.Visit, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.Visit, err error)
	FindInBatches(result *[]*domain.Visit, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*domain.Visit) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IVisitDo
	Assign(attrs ...field.AssignExpr) IVisitDo
	Joins(fields ...field.RelationField) IVisitDo
	Preload(fields ...field.RelationField) IVisitDo
	FirstOrInit() (*domain.Visit, error)
	FirstOrCreate() (*domain.Visit, error)
	FindByPage(offset int, limit int) (result []*domain.Visit, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IVisitDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (v visitDo) Debug() IVisitDo {
	return v.withDO(v.DO.Debug())
}

func (v visitDo) WithContext(ctx context.Context) IVisitDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v visitDo) ReadDB() IVisitDo {
	return v.Clauses(dbresolver.Read)
}

func (v visitDo) WriteDB() IVisitDo {
	return v.Clauses(dbresolver.Write)
}

func (v visitDo) Session(config *gorm.Session) IVisitDo {
	return v.withDO(v.DO.Session(config))
}

func (v visitDo) Clauses(conds ...clause.Expression) IVisitDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v visitDo) Returning(value interface{}, columns ...string) IVisitDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v visitDo) Not(conds ...gen.Condition) IVisitDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v visitDo) Or(conds ...gen.Condition) IVisitDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v visitDo) Select(conds ...field.Expr) IVisitDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v visitDo) Where(conds ...gen.Condition) IVisitDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v visitDo) Order(conds ...field.Expr) IVisitDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v visitDo) Distinct(cols ...field.Expr) IVisitDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v visitDo) Omit(cols ...field.Expr) IVisitDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v visitDo) Join(table schema.Tabler, on ...field.Expr) IVisitDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v visitDo) LeftJoin(table schema.Tabler, on ...field.Expr) IVisitDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v visitDo) RightJoin(table schema.Tabler, on ...field.Expr) IVisitDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v visitDo) Group(cols ...field.Expr) IVisitDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v visitDo) Having(conds ...gen.Condition) IVisitDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v visitDo) Limit(limit int) IVisitDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v visitDo) Offset(offset int) IVisitDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v visitDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IVisitDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v visitDo) Unscoped() IVisitDo {
	return v.withDO(v.DO.Unscoped())
}

func (v visitDo) Create(values ...*domain.Visit) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v visitDo) CreateInBatches(values []*domain.Visit, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v visitDo) Save(values ...*domain.Visit) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v visitDo) First() (*domain.Visit, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.Visit), nil
	}
}

func (v visitDo) Take() (*domain.Visit, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.Visit), nil
	}
}

func (v visitDo) Last() (*domain.Visit, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.Visit), nil
	}
}

func (v visitDo) Find() ([]*domain.Visit, error) {
	result, err := v.DO.Find()
	return result.([]*domain.Visit), err
}

func (v visitDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.Visit, err error) {
	buf := make([]*domain.Visit, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v visitDo) FindInBatches(result *[]*domain.Visit, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v visitDo) Attrs(attrs ...field.AssignExpr) IVisitDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v visitDo) Assign(attrs ...field.AssignExpr) IVisitDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v visitDo) Joins(fields ...field.RelationField) IVisitDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v visitDo) Preload(fields ...field.RelationField) IVisitDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v visitDo) FirstOrInit() (*domain.Visit, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.Visit), nil
	}
}

func (v visitDo) FirstOrCreate() (*domain.Visit, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.Visit), nil
	}
}

func (v visitDo) FindByPage(offset int, limit int) (result []*domain.Visit, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v visitDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v visitDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v visitDo) Delete(models ...*domain.Visit) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *visitDo) withDO(do gen.Dao) *visitDo {
	v.DO = *do.(*gen.DO)
	return v
}
